TRAIN_DATASET_PATH: data/datasets/train_full.json
VAL_DATASET_PATH: data/datasets/val_full.json
TEST_DATASET_PATH: data/datasets/test_full.json
NUM_WORKERS: 2
EXPERIMENT_PATH: experiments/fact-reranking
WIKIDATA_PATH: data/wikidata
MODEL_NAME: "fact-reranker"
DEVICE: "cuda"